theme = "dracula_at_night"

[editor]
bufferline = "always"
color-modes = true
default-line-ending = "lf"
insert-final-newline = true
true-color = true
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# Disable automatically popups of signature parameter help
# auto-signature-help = false
# Show LSP messages in the status line
display-messages = true
# display-inlay-hints = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

separator = "┊"

left = ["mode", "spinner", "file-name", "read-only-indicator"]
center = ["version-control", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "primary-selection-length", "file-encoding"]

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-J = ["extend_to_line_bounds", "yank", "paste_after"]
A-K = ["extend_to_line_bounds", "yank", "paste_before"]
C-q = ":buffer-close"
X = ["extend_line_up", "extend_to_line_bounds"]

[keys.select]
A-x = "extend_to_line_bounds"
X = ["extend_line_up", "extend_to_line_bounds"]

