[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server]
deno = { command = "deno", args = [ "lsp" ]}

# [[language]]
# name = "typescript"
# language-servers = [ "deno" ]
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "ts" ] }
# auto-format = true

# [[language]]
# name = "javascript"
# language-servers = [ "deno" ]
# formatter = { command = 'deno', args = ["fmt", "-", "--ext", "js" ] }
# auto-format = true

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
